name: tsx
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - mysql-connector-python==8.0.26
  - scipy==1.7.1
  - sqlalchemy==1.4.23
  - pyproj==3.1.0
  - pandas==1.3.2
  - shapely==1.7.1
  - tqdm==4.62.2
  - fiona==1.8.20
  - numpy==1.21.2
  - openpyxl==3.0.7
  - mysql-client
  - tzlocal
