
PS1="TSX:\w# "

cat <<EOF

Welcome to the TSX Workflow docker image.

EOF

if ! mysql -sNe "SELECT 1" > /dev/null; then
	echo
	echo Unable to connect to mysql. Please ensure mysql is running by opening a separate terminal window and running:
	echo -e "    \e[1mdocker compose up\e[0m"
	exit
fi



if [ -z "$(mysql -sNe "SHOW TABLES")" ]; then
	mysql < /seed/db/sql/create.sql
	mysql < /seed/db/sql/init.sql
	mysql < /seed/sample-data/seed.sql
fi

# Fixes: ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed
# See https://github.com/PDAL/PDAL/issues/2544
export PROJ_LIB=/opt/conda/share/proj

cp -rn /seed/* /root/data
cd /root/data
