# To run tests:
# podman compose -f containers/docker-compose.yml run --build --rm test

# To run workflow_cli
# podman compose -f containers/docker-compose.yml run --rm workflow_cli

version: "3.1"
name: tsx
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tsx
      MYSQL_USER: tsx
      MYSQL_PASSWORD: tsx
    ports:
      - "6033:3306"
    volumes:
      - tsx_mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
      interval: 1s
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8033:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
  workflow_cli:
    profiles: ["cli"] # prevents this service from starting automatically
    image: ghcr.io/nesp-tsr3-1/tsx-workflow:latest
    # build:
    #   context: ..
    #   dockerfile: containers/Dockerfile-conda
    #   target: prod
    depends_on:
      mysql:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    volumes:
      - ./data:/root/data
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  test:
    profiles: ["test"]
    build:
      context: ..
      dockerfile: containers/Dockerfile-conda
      target: test
    depends_on:
      mysql:
        condition: service_healthy
  jupyter:
    profiles: ["jupyter"]
    build:
      context: ..
      dockerfile: containers/Dockerfile-conda
      target: jupyter
    ports:
      - 8034:8888
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  tsx_mysql_data:
