= Custodian Feedback

The custodian feedback functionality facilitates communication between the TSX team and custodians regarding their datasets and the outputs produced from those datasets by the TSX workflow.

== Concepts

=== Taxon Dataset

Custodian feedback is always managed at the "taxon dataset" level. A taxon dataset refers data for a single taxon from a single dataset. For datasets with only one taxon there is only one taxon dataset, but in general a dataset may contain data for many taxa and therefore have many taxon datasets.

=== Form

Custodian feedback is entered into a custodian feedback form. The form asks questions relating to various aspects of the data and how it was collected. It also contains plots and data summaries generated by the TSX workflow, along with questions relating to those outputs.

=== Form Type

There are three different types of custodian feedback forms:

 - Integrated
 - Admin
 - Spreadsheet

Integrated forms are filled out by custodians, and a new integrated form is generated each time the custodian imports new data into their dataset.

Admin forms are filled out by Administrators. There is always exactly one Admin form per taxon dataset, which can be updated at any time.

Spreadsheet forms are archived, downloadable Excel spreadsheets containing feedback that was collected before the web-based custodian feedback functionality existed.

=== Form Status

Each feedback form has one of the following status:

 - Archived
 - Complete
 - Draft Saved
 - Incomplete

Integrated forms begin with a status of _Incomplete_. If a custodian begins filling out the form and saves their changes, the status changes to _Draft Saved_. If they submit a completed form, the status changes to _Complete_. If new data is uploaded for a taxon dataset, a new integrated form is created with status _Incomplete_. Any existing integrated form is changed to _Archived_ status if it was complete, or deleted otherwise.

Admin forms also begin with a status of _Incomplete_, and progress to _Draft Saved_ when changes are saved, or _Complete_ if a completed. If new data is uploaded for a taxon dataset, the admin form is not deleted but its status changes back to _Incomplete_ and the data summaries and plots are updated to reflect the new data.

Spreadsheet forms always have a status of _Archived_.

If a taxon is removed from a dataset by uploading a new file, any archived or completed forms belonging to the deleted taxon dataset are kept.

== Taxon Dataset Listing

Page URL: https://tsx.org.au/data/custodian_feedback

The entry point for accessing custodian feedback functionality is entitled _Custodian Feedback Forms_, however it is actually a listing of taxon datasets.

=== Table

Custodians have access to integrated and spreadsheet forms relating to any of their datasets. Administrators have access to custodian feedback for all taxon datasets. Program Managers do not have any special access to custodian feedback.

The taxon datasets which the user has access to are listed in a table with the following columns:

[cols="1,1"]
|===
|Column |Description

|Taxon Dataset
|The name of the dataset, the name of the taxon, and an taxon dataset ID which is formed by combining the dataset ID and the taxon ID. If the taxon dataset no longer exists in the most recent data upload, a "Taxon Dataset removed" label is shown.

|Latest form created
|The most recent creation date of an integrated form in the taxon dataset.

|Latest form modified
|The most recent modification date of an integrated form in the taxon dataset.

|Latest form status
|The status of the most recent integrated form in the taxon dataset.

|Admin status
|The status of the admin form in the taxon dataset. This column is visible to Administrators users only.
|===


The table is initially sorted by _Latest form created_ in reverse-chronological order, but it can be sorted by any column by clicking on the corresponding heading.

Clicking on any taxon dataset leads to the <<Form Listing>> page for that dataset.


=== Search Bar

A search bar above the table allows taxon datasets to be searched by dataset description and taxon scientific name. As text is entered into the search bar, the table is automatically filtered to show only matching records.

=== Taxon Dataset Count

The interface displays the total number of taxon datasets accessible by the user, and the number of taxon datasets currently displayed based on the search criteria.


== Form Listing

This page lists the indivual forms within a single taxon dataset.

The title of page is the taxon scientific name and the taxon dataset ID. Below this, the dataset description is shown and links to the corresponding xref:datasets.adoc#dataset-details[Dataset Details] page.

If the taxon has been deleted from the dataset, a highlighted message reads:

[quote]
The most recent data import for this dataset does not contain any records with this taxon.

=== Table

The forms are displayed in a table with the following columns:

[cols="1,1"]
|===
|Column |Description

|Form
|The scientific name of the taxon, the taxon dataset ID and a button to 'Start' (if _Incomplete_) or 'Edit' (if _Draft Saved_ or _Complete_) the form

|Created
|The creation date of the form

|Modified
|The most recent modification date of the form

|Status
|The <<Form Status,status>> of the form

|Type
|The <<Form Type,type>> of the form

|Action
|A button to download the form. Integrated forms are downloadable in PDF format, Admin forms in CSV format, and Spreadsheet forms in XSLX (Excel) format.
|===

Admin forms are only visible to Administrators.

Clicking on the 'Start' or 'Edit' button, immediately navigates to the <<Form Editing>> interface for that form.

== Form Editing

The custodian form contains more than 30 questions and has some variations depending on the form type.

=== Page Structure

The form itself is presented in a single page that is quite long.

A fixed (non-scrolling) sidebar on the left contains links to the main sections of the form, and automatically highlights the current section based on how far the user has scrolled down the page.

The sidebar also contains buttons to save and/or submit the form:

 - The _Save Draft and Close_ button is only shown for non-completed surveys. When clicked, the form is saved, its status is set to _Draft Saved_, and the user is directed back to the <<Form Listing>> page.
 - The _Submit_ button attempts to submit the form. If any fields contain invalid data, they are highlighted with appropriate messages. Otherwise, the form is saved, its status is set to _Complete_, and the user is directed back to the <<Form Listing>> page.

=== Conditions and Consent

Non-admin users are required to acknowledge conditions listed in this section and indicate their consent by ticking a checkbox and entering their name.

=== Formal vs. Informal

Admin surveys can be classified as informal or formal.

All admin surveys for newly created datasets are formal.

Informal surveys exist for old datasets where only limited information is available. As such, informal surveys only consist of a few questions:

 - 1. Does the custodian agree with the trend? If no or unsure, what specifically do they disagree with? (`TrendAgree`/`TrendAgreeComments`)
 - 2. What reference year has the custodian suggested for their trend? (`StartYear`/`StartYearComments`)
 - 3. What end year has the custodian suggested for their trend? (`EndYear`/`EndYearComments`)
 - Please add any additional comments from the custodian below. (`CustodianComments`)
 - INTERNAL ONLY: Please add any additional comments on the dataset below. Include your initials and date where possible. (`InternalComments`)

Informal surveys can be changed to formal surveys, allowing the full suite of Admin survey questions to be filled out. However, the reverse is not true - it is not permitted to change a formal survey back to an informal one. A confirmation dialog is shown to the user when changing a survey to from informal to formal to ensure they understand they are making an irreversable change.

=== Data citation and monitoring aims

The dataset citation as generated by TSX (see xref:datasets.adoc#metadata-fields[Metadata fields]) is shown at the top of this section.

Then the following fields are shown:

[cols="1,1,2"]
|===
|Field name |Field type/options |Label

.2+|`CitationAgree`
.2+|Yes, No
|*Integrated*

1. Do you agree with the above suggested citation for your data? If no, please indicate how to correctly cite your data.

|*Admin*

1. Does the custodian agree with the suggested citation? If no, what changes have they suggested to correctly cite their data?

|`CitationAgreeComments`
|Free text
|

.2+|`MonitoringForTrend`
.2+|Yes, No, Unsure
|*Integrated*

2. Has your monitoring program been explicitly designed to detect population trends over time? If no / unsure, please indicate the aims of your monitoring.

|*Admin*

2. Is the monitoring program explicitly designed to detect population trends over time? If no or unsure, what are the aims of their monitoring?

|`MonitoringForTrendComments`
|Free text
|

.2+|`AnalyseOwnTrends`
.2+|Yes, No
|*Integrated*

3. Do you analyse your own data for trends? If no, please indicate why.

|*Admin*

3. Does the custodian analyse their own data for trends? If no, please indicate why.

|`AnalyseOwnTrendsComments`
|Free text
|

.2+|`Pop1750`
.2+|Free text
|*Integrated*

4. Can you estimate what percentage (%) of your species’ population existed in Australia at the start of your monitoring (assuming this was 100% in 1750)?

|*Admin*

4. What has the custodian estimated to be the percentage (%) of the species’ population that existed in Australia at the start of the monitoring (assuming this was 100% in 1750)?

|`Pop1750Comments`
|Free text
|

|===


=== Data summary and processing

At the top of this section the following outputs are displayed:

* A xref:downloads.adoc#monitoring-consistency-plot[Monitoring Consistency Plot]
* A xref:downloads.adoc#site-map[Site Map]
* A data processing summary table
* A site management summary table

The data processing summary table has one row for every distinct combination of search type and unit in the taxon dataset, and contains the following columns:

 - Search Type Description
 - Unit of Measurement
 - Unit Type
 - Data Processing Type
 - Method of Aggregation

The second data summary table has one row for every distinct combination of Management Category and Management Comments, and contains the following columns:

 - Management Category
 - Management Comments
 - Number of Sites

Below these outputs are the following fields

[cols="1,1,2"]
|===
|Field name |Field type/options |Label


.2+|`DataSummaryAgree`
.2+|Yes, No
|*Integrated*

5. Does the above data summary and plots appear representative of your dataset?

|*Admin*

5. Does the custodian agree with the data summary? If no, what specifically do they disagree with?

|`DataSummaryAgreeComments`
|Free text
|

.2+|`ProcessingAgree`
.2+|Yes, No, Unsure
|*Integrated*

6. Do you agree with how your data were handled? If no, please suggest an alternative method of aggregation.

|*Admin*

6. Does the custodian agree with how the data were processed? If no, what alternative method of aggregation have they suggested?

|`ProcessingAgreeComments`
|Free text
|

|===

=== Statistics and trend estimate

At the top of this section a table of statistics for the raw and aggregated is shown.

Raw data statistics:

 - Period of monitoring (years)
 - Number of data points (surveys)
 - Range of raw data (counts)
 - Number of 0 counts

Aggregated data statistics:

 - Number of repeatedly monitored sites (time series)
 - Time-series length (years)
 - Time-series sample years (years)
 - Time-series completeness (%)
 - Time series sampling evenness (0 = very even sampling)

For the time-series statistics, both a mean value and a standard deviation are displayed.

Below these statistics, the following fields are shown:

[cols="1,1,2"]
|===
|Field name |Field type/options |Label


.2+|`StatisticsAgree`
.2+|Yes, No
|*Integrated*

7. Do the above statistics appear representative of your dataset?

|*Admin*

7. Does the custodian agree with the data statistics (raw and aggregated)? If no, what specifically do they disagree with?

|`StatisticsAgreeComments`
|Free text
|

|===


Below this, an xref:downloads.adoc#population-trend[population trend plot] is displayed. A _Customise Trend_ button allows the user to select a different reference year, final year and list of sites to include in the trend. The user must click _Update Trend_ to apply these changes, and the updated trend may take some time to generate. If the trend has been customised, a warning message says "Please note: you are not viewing the original trend in full", accompanied by a _Reset Trend_ button.

This is followed by the following fields


[cols="1,1,2"]
|===
|Field name |Field type/options |Label


.2+|`TrendAgree`
.2+|Yes, No
|*Integrated*

8. Do you agree with the trend estimate? If no or unsure, please elaborate (include detail on trends for specific sites where relevant).

|*Admin*

8. Does the custodian agree with the trend? If no or unsure, what specifically do they disagree with?

|`TrendAgreeComments`
|Free text
|


.2+|`StartYear`
.2+|Free text
|*Integrated*

9. Looking at the trend for your data, what should be the reference year at which the index should start?

|*Admin*

9. What reference year has the custodian suggested for their trend?

|`StartYearComments`
|Free text
|

.2+|`EndYear`
.2+|Free text
|*Integrated*

10. Looking at the trend for your data, what should be the year at which the index should end?

|*Admin*

10. What end year has the custodian suggested for their trend?

|`EndYearComments`
|Free text
|

|===

=== Data suitability

This section consists of the following multiple-choice fields, which are presented in a table rather than the usual layout.

[cols="8,1,7"]
|===
|Field name/label/description 2+|Options


.6+|`StandardisationOfMethodEffort`

*11. Standardisation of method effort*

This data suitability indicator rates the degree of standardisation of monitoring method/effort and is assessed to the data source level by enquiring with the data custodian and examining data. 

| 6 | Pre-defined sites/plots surveyed repeatedly through time using a single standardised method and effort across the whole monitoring program
| 5 | Pre-defined sites/plots surveyed repeatedly through time with methods and effort standardised within site units, but not across program - i.e. different sites surveyed have different survey effort/methods
| 4 | Pre-defined sites/plots surveyed repeatedly through time with varying methods and effort
| 3 | Data collection using standardised methods and effort but surveys not site-based (i.e. surveys spatially ad-hoc). Post-hoc site grouping possible - e.g. a lot of fixed area/time searches conducted within a region but not at pre-defined sites
| 2 | Data collection using standardised methods and effort but surveys not site-based (i.e. surveys spatially ad-hoc). Post-hoc site grouping not possible
| 1 | Unstandardised methods/effort, surveys not site-based




.5+|`ObjectiveOfMonitoring`

*12. Objective of monitoring*

This field indicates the objective of the monitoring.

| 4 | Monitoring for targeted conservation management
| 3 | Monitoring for general conservation management – ‘surveillance’ monitoring
| 2 | Baseline monitoring
| 1 | Monitoring for community engagement
| NA | Not defined




.4+|`ConsistencyOfMonitoring`

*13. Consistency of monitoring*

This data suitability indicator rates the degree of consistency by which the same sites were repeatedly monitored over time.

| 4 | Balanced; all (or virtually all) sites surveyed in each year sampled (no, or virtually no, site turnover)
| 3 | Imbalanced (low turnover); sites surveyed consistently through time as established, but new sites are added to program with time.
| 2 | Imbalanced (high turnover); new sites are surveyed with time, but monitoring of older sites is often not always maintained.
| 1 | Highly Imbalanced (very high turnover); different sites surveyed in different sampling periods. Sites are generally not surveyed consistently through time (highly biased)


.3+|`MonitoringFrequencyAndTiming`

*14. Monitoring frequency and timing*

This data suitability indicator rates whether the taxon was monitored with an appropriate frequency and during an appropriate season/timing.

| 3 | Monitoring frequency and timing appropriate for taxon
| 2 | Monitoring frequency or timing inappropriate for taxon for majority of data.
| 1 | Monitoring ad-hoc; no pattern to surveys for majority of data (incidental)


.3+|`AbsencesRecorded`

*15. Were absences recorded systematically?*

Absences are non-detections of taxa i.e. where 0 counts of a species are recorded.

|| Yes
|| No
|| Partially (for some of the survey period)

|===

Below this, one more question is shown in the regular layout:

[cols="1,1,2"]
|===
|Field name |Field type/options |Label


.2+|`DataSuitabilityComments`
.2+|Free text
|*Integrated*

Please add any additional comments on data suitability and the criteria below.

|*Admin*

What additional comments on data suitability and the criteria has the custodian provided?

|===

=== Additional comments (integrated)

For integrated forms, the following field is shown:

[cols="1,1,2"]
|===
|Field name |Field type/options |Label


|`AdditionalComments`
|Free text
|Please provide any additional comments about this dataset and/or trend below.

For admin forms, additional comment fields are shown further down the form.

|===

=== Monitoring program funding, logistics and governance (integrated)

This optional section contains many questions, however only the first question is enabled at first:

[cols="8,1,7"]
|===
|Field name/label 2+|Options


.4+|`CostDataProvided`

Questions 17 to 32 below are optional. We hope you are interested in providing some further information about your monitoring program.

16. Please indicate if you would prefer to provide this information via a phone or video call with our project team

|1| I will provide answers to questions 17 to 32 in this feedback form.
|2| I have already provided answers to questions 17 to 32 in a separate feedback form. Please copy them across.
|3| I prefer to be contacted by phone or video call to answer questions 17 to 32
|4| I will not be providing answers to questions 17 to 32

|===

The result of selecting each option is as follows:


 - Option 1: the remaining questions in the section are enabled.

 - Option 2: a dropdown menu showing any previous custodian feedback forms relating to the dataset (including other taxa) appears. The menu items show the dataset ID, taxon scientific name and last modification date of each form. When the user selects a previous form and clicks _Copy Answers_, the remaining fields in this section are populated from the selected form. The fields are also enabled so that they can be edited as required.

 - Option 3: a field appears prompting the user to enter their contact email address or phone number. (MonitoringProgramInformationContact). All remaining fields remain disabled.

 - Option 4: all remaining fields remain disabled.

The remaining fields in this section are as follows:

[cols="2,4,1"]
|===
|Field name | Field label |Field type/options


| 2+| 17. Effort: How much time on average per year was spent on project labour, i.e. data collection in the field?

|`EffortLabourPaidDaysPerYear` | 17a. Days/year paid labour | Free text
|`EffortLabourVolunteerDaysPerYear` | 17b. Days/year volunteered time | Free text

| 2+| 18. Effort: How much time on average per year was spent on project overheads, e.g. data collation and dataset maintenance?

|`EffortOverheadsPaidDaysPerYear` | 18a. Days/year paid labour | Free text
|`EffortOverheadsVolunteerDaysPerYear` | 18b. Days/year volunteered time | Free text

| 2+| 19. Effort: Approximately how many people were involved in the last bout of monitoring (including both field and office work)

|`EffortPaidStaffCount` | 19a. Paid staff | Free text
|`EffortVolunteerCount` | 19b. Volunteers | Free text


|`FundingCostPerSurveyAUD` | 20. Funding: How much do you think in AUD$ a single survey costs (not counting in-kind support)? | Free text

|`FundingTotalInvestmentAUD` | 21. Funding: Can you estimate in AUD$ the total investment in the dataset to date (again not counting in-kind support)? | Free text

| 2+| 22. Funding: Who has been paying for the monitoring? (e.g. government grants, research funds, private donations etc. – list multiple funding sources if they have been needed over the years)

|`FundingSourceGovernmentGrants` | 22a. Government grants | Yes, No
|`FundingSourceResearchFunds` | 22b. Research funds | Yes, No
|`FundingSourcePrivateDonations` | 22c. Private donations | Yes, No
|`FundingSourceOther` | 22d. Other | Free text
|`FundingSourceCount` | 22e. Can you estimate the total number of funding sources so far? | Free text

|`Leadership` | 23. Leadership: Who has been providing the drive to keep the monitoring going after the baseline was established? | Free text

| 2+| 24. Impact: Are data being used to directly inform management of the threatened species or measure the effectiveness of management actions?
|`ImpactUsedForManagement` | 24a. | Yes, No
|`ImpactUsedForManagementComments` | 24b. Please expand | Free text

|`ImpactOrganisationResponsible` | 25. Impact: Is your organisation responsible for managing this species in the monitored area? | Free text

|`ImpactManagementChanges` | 26. Impact: Can you describe any management that has changed because of the monitoring? | Free text

|`DataAvailability` | 27. Data availability: Is your monitoring data readily available to the public (e.g. through reports, or on website). If not, can the public access it? | Free text

| 2+| 28. Succession: Do you have commitments to extend the monitoring into the future?
|`SuccessionCommitment` | 28a. | Yes, No
|`SuccessionCommitmentComments` | 28b. Please expand | Free text

| 2+| 29. Succession: Have you developed a plan for continual monitoring when the current organisers/you need to stop?
|`SuccessionPlan` | 29a. | Yes, No
|`SuccessionPlanComments` | 29b. Please expand | Free text

| 2+| 30. Design: Was there thought about the statistical power of the monitoring when it was started (i.e. the probability that change could be detected?)
|`DesignStatisticalPower` | 30a. | Yes, No
|`DesignStatisticalPowerComments` | 30b. Please expand | Free text


| 2+| 31. Design: Is anything other than the numbers of threatened species being monitored at the same time that could explain changes in abundance (e.g. prevalence of a threat, fire, breeding success, etc?)
|`DesignOtherFactors` | 31a. | Yes, No
|`DesignOtherFactorsComments` | 31b. Please expand | Free text

| 2+| 32. Co-benefits: Is the monitoring program for this species also collecting trend information on other threatened species?
|`CoBenefitsOtherSpecies` | 32a. | Yes, No
|`CoBenefitsOtherSpeciesComments` | 32b. Please expand | Free text



|===


=== Monitoring program funding, logistics and governance (admin)

For admin forms, this section contains the following fields:


[cols="1,1,2"]
|===
|Field name |Field type/options |Label

|`CostDataProvided` | Yes, No | 16. Has the custodian answered the optional questions about funding, logistics and governance?

|`EstimatedCostDataset` | Free text | 17. Where the custodian has provided funding data, what value have they estimated as the total investment in the dataset to date (not counting in-kind support)?

|`CostDataProvidedComments` | Free text | 18. Please add any additional comments from the custodian about the monitoring program below.

|===

=== Additional comments (admin)

For admin forms, this section contains the following fields:


[cols="1,1,2"]
|===
|Field name |Field type/options |Label

|`CustodianComments` | Free text | Please add any additional comments from the custodian below.

|`InternalComments` | Free text | INTERNAL ONLY: Please add any additional comments on the dataset below. Include your initials and date where possible.

|===
