
==== Install Prerequisite software

*MySQL Community Edition 8*

Download: https://dev.mysql.com/downloads/mysql/

Choose the ‘Developer Default’ Setup Type which includes MySQL Workbench - a graphical user interface to the database (not required to run the workflow but makes it easier to inspect the database). At the ‘Check Requirements’ installation menu click ‘next’. Follow the default installation settings unless indicated otherwise. Under ‘Accounts and Roles’ choose a password and make sure to remember it later on.

*Anaconda*

Download: https://www.anaconda.com/products/individual

The rest of the required software can be installed using Anaconda. Anaconda enables you to conveniently download the correct versions of Python, R and libraries in one step, and avoids any conflicts with existing versions of these software that may already exist on your computer.

==== Download TSX Workflow and Sample Data

The latest version of the TSX workflow software can be downloaded at: https://github.com/nesp-tsr3-1/tsx/archive/master.zip .

Download and unzip into a directory of your choosing (or clone using Git if you prefer). To make it easier to follow this guide, rename the `tsx-master` directory to `TSX_HOME`. (Depending on how you unzip the file, you may end up with a `tsx-master` directory containing another `tsx-master` directory – it is the innermost directory that should be renamed.)

Now open Anaconda and use the 'Import Environment' function to import the `conda-environment.yml` file inside the `TSX_HOME` directory. Importing this environment will take some time as Anaconda downloads and installs the necessary software. Once the environment has been imported, click the 'play' icon next to the environment to open a Command Prompt which can be used to run the TSX workflow.

This guide will make extensive use of this Command Prompt. All commands assume that your current working directory is `TSX_HOME`, so the first command you will need to run is `cd` to change your working directory.

==== Database Setup

Start the MySQL command-line client and create a database called “tsx”. In this guide we will simply be accessing MySQL as the default “root” user. (Note that in a shared environment it is advised to create a separate user that has limited access to the tsx database only.)

----
mysql –u root
mysql> create database tsx;
mysql> quit;
----

Now run the following commands to populate the database structure and lookup tables.
----
mysql –u root tsx < db\sql\create.sql
mysql –u root tsx < db\sql\init.sql
mysql –u root tsx < sample-data\seed.sql
----

Understanding the database schema is not essential to following the steps in this guide, but is recommended if you want to gain an in-depth understanding of the processing.
// TODO: link to database schema

==== Update Workflow Configuration File

Copy the sample configuration file from `TSX_HOME\tsx.conf.example.windows` to `TSX_HOME\tsx.conf`.
----
copy tsx.conf.example.windows tsx.conf
----
