==== Install Prerequisite software

The following instructions have been tested on Ubuntu Linux 18.04. If you are using a different Linux distribution you will need to adapt these commands for your system. If you are using macOS, we recommend using homebrew (https://brew.sh) to install dependencies.

Run the following commands to install prerequisite software:

----
sudo apt-get update
sudo apt-get install -y nginx mysql-server python python-pip git
----

Install `uv` by following the instructions at https://docs.astral.sh/uv/getting-started/installation/

==== Download TSX Workflow and Sample Data

Run the following command to download the TSX workflow into a folder named `tsx`

----
git clone https://github.com/nesp-tsr3-1/tsx.git
----

Then enter the `tsx` directory and run the following commands:

----
uv sync
----

NOTE: Since we are using the `uv` package manager, all python commands in this guide should be prefixed by `uv run` (e.g. `uv run python -m tsx.process -c t1_aggregation`). Alternatively, you may wish to start a new shell with `uv run bash` and run all commands from there without the `uv run` prefix.

==== Database Setup

Initialise the database by running:
----
sudo setup/setup-database.sh
sudo mysql tsx < sample-data/seed.sql
----

Understanding the database schema is not essential to following the steps in this guide, but is recommended if you want to gain an in-depth understanding of the processing.
// TODO: link to database schema

==== Update Workflow Configuration File

Copy the sample configuration file from `TSX_HOME\tsx.conf.example` to `TSX_HOME\tsx.conf`.
----
cp tsx.conf.example tsx.conf
----
