# Basic example of running the LPI on the output of the TSX workflow

# You can run it from the command line like this:
# R
# > source("lpi.R")
#
# Or in Rstudio like this
# rstudio lpi.R
# (Then press shift + ctrl + S)

library(rlpi)

in_file <- "../sample-data/export/lpi-filtered.csv"

# Load 'wide table' file generated by TSX workflow
lpi_data <- read.csv(in_file, na.strings = "", quote = "\"",sep = ",")

# Prepare data for LPI
infile_name <- create_infile(lpi_data, name="infile", start_col_name="X1950", end_col_name="X2015")

# Run LPI
lpi <- LPIMain(infile_name,
	REF_YEAR=2000,
	PLOT_MAX=2015,
	BOOT_STRAP_SIZE=1000,
	VERBOSE=TRUE,
	goParallel=TRUE,
	title="TSX",
	plot_lpi=0,
	save_plots=0)

# View a plot
ggplot_lpi(lpi)
